# ---------------------------------
# CSI Controller Server
# ---------------------------------
#
# Runs single driver controller server (driver + provisioner + attacher + snapshotter) on one of the nodes
#

apiVersion: v1
kind: ServiceAccount
metadata:
  name: "{{ .Values.controller.name }}-{{ .Values.serviceAccountPostfix }}"
  namespace: {{ .Release.Namespace }}
