apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: "{{ .Values.node.name }}-{{ .Values.clusterRoleBindingPostfix }}"
subjects:
  - kind: ServiceAccount
    name: "{{ .Values.node.name }}-{{ .Values.serviceAccountPostfix }}"
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: "{{ .Values.node.name }}-{{ .Values.clusterRolePostfix }}"
  apiGroup: rbac.authorization.k8s.io
