apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.config.secretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: red-csi-driver-block
    chart: red-csi-driver-block
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
stringData:
  red-csi-driver-block-config.yaml: |-
{{ toYaml .Values.config | indent 4 }}
