# Nginx pod with dynamic storage creation and NVMEOF device mount using RED Block CSI driver
#
# $ kubectl apply -f examples/kubernetes/dynamic-mount-volume-pod.yaml
#
# --------------------------------------
# RED CSI Driver - Storage Class
# --------------------------------------

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: red-block-csi-driver-sc-nginx-dynamic-mount
provisioner: block.csi.red.ddn.com
#allowVolumeExpansion: true
parameters:
  # required parameters
  account: clu1/red/csiAccount
  service: red/csiService
  # optional params
  #instances: "1,2,3"
  #owneruid: "1000"
  #groupuid: "1000"
  #perms: "0660"
---

# ------------------------------------------------
# RED CSI Driver - Persistent Volume Claim
# ------------------------------------------------

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: red-block-csi-driver-pvc-nginx-dynamic-mount
spec:
  storageClassName: red-block-csi-driver-sc-nginx-dynamic-mount
  accessModes:
  - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
---
# ---------
# Nginx pod
# ---------

apiVersion: v1
kind: Pod
metadata:
  name: nginx-dynamic-mount-volume
spec:
  containers:
  - image: nginx
    imagePullPolicy: IfNotPresent
    name: nginx
    ports:
    - containerPort: 80
      protocol: TCP
    volumeMounts:
    - mountPath: /mountedDisk
      name: red-block-csi-driver-data
  volumes:
  - name: red-block-csi-driver-data
    persistentVolumeClaim:
      claimName: red-block-csi-driver-pvc-nginx-dynamic-mount
      readOnly: false

