# ------------------------------------------------
# RED CSI Driver - Persistent Volume Claim
# ------------------------------------------------

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: red-block-csi-driver-pvc-nginx-dynamic
spec:
  storageClassName: red-block-csi-driver-sc-nginx-dynamic
  accessModes:
  - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
---
