# Nginx pod with dynamic storage creation and NVMEOF device mount using RED Block CSI driver
#
# $ kubectl apply -f examples/kubernetes/dynamic-mount-volume-pod.yaml
#
# --------------------------------------
# RED CSI Driver - Storage Class
# --------------------------------------

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: red-block-csi-driver-sc-with-secret
provisioner: block.csi.red.ddn.com
#allowVolumeExpansion: true
parameters:
  # required parameters
  account: c1/red/csi-multi-tenancy
  service: red/csi-multi-tenancy
  # optional params
  #instances: "1,2,3"
  #owneruid: "1000"
  #groupuid: "1000"
  #perms: "0660"
  csi.storage.k8s.io/provisioner-secret-name: red-csi-multi-tenancy1
  csi.storage.k8s.io/provisioner-secret-namespace: red-block-csi
  csi.storage.k8s.io/controller-expand-secret-name: red-csi-multi-tenancy1
  csi.storage.k8s.io/controller-expand-secret-namespace: red-block-csi
  csi.storage.k8s.io/node-stage-secret-name: red-csi-multi-tenancy1
  csi.storage.k8s.io/node-stage-secret-namespace: red-block-csi
  csi.storage.k8s.io/node-publish-secret-name: red-csi-multi-tenancy1
  csi.storage.k8s.io/node-publish-secret-namespace: red-block-csi
---
